#!/bin/bash
docker create -v /var/jenkins_home -v /root/.m2 -v /root/.ssh --name jenkins-dv jenkins
docker run --volumes-from jenkins-dv --name helper busybox true
docker cp settings.xml helper:/root/.m2/
docker cp known_hosts helper:/root/.ssh/
docker rm helper
