#!/bin/bash
docker create -v /var/jenkins_home -v /root/.m2 --name jenkins-dv jenkins
docker run --volumes-from jenkins-dv --name helper busybox true
docker cp settings.xml helper:/root/.m2/
docker rm helper
