version: '3.7'

services:
  results:
    entrypoint:
      - "/usr/bin/java"
      - "-Xdebug"
      - "-Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=9999"
      - "-jar"
      - "catholicon-ms-matchcard.jar"
    ports:
      - "9999:9999"
    expose:
      - "9999"